CREATE TABLE IF NOT EXISTS users
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS news (
                                    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                    owner int NOT NULL REFERENCES users(id),
                                    name VARCHAR(255),
                                    description VARCHAR(4000)
);

insert into users (fullname, email, password) values ( 'Автор', '123@yu.ru', decode('16', 'hex'));

insert into news (owner, name, description) values (1, 'Пост1', 'морген дропнуопнул клип!');

select * from users